from math import ceil
from random import getrandbits

ONE_MB = 1 * 1024 * 1024
ONE_GB = ONE_MB * 1024
DEFAULT_BLOCK_SIZE = 64 * ONE_MB
DEFAULT_BLOCKS_PER_FILE = ceil((10 * ONE_GB) / DEFAULT_BLOCK_SIZE)
DEFAULT_BLOCKS_PER_FILE_SPREAD = DEFAULT_BLOCKS_PER_FILE / 4
DEFAULT_NUMBER_OF_FILES = 50
